//using System;
//using System.Collections.Generic;
//using System.Text;

//namespace Skyline.Office.Excel.Enums
//{
//    public enum ExcelColor
//    {
//        Black = 1,
//        White=2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//        White = 2,
//    }
//}
