name: Skyline Release

on:
  push:
    branches: release/skyline

jobs:
  build:
    name: Build Project Skyline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Shared/Skyline.Shared.sln
    - name: Build
      run: dotnet build Shared/Skyline.Shared.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Shared/Skyline.Shared.sln --no-restore --verbosity normal

  publish:
    needs: [build]
    name: Publish Skyline To NuGet
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish
      run: |
        dotnet build Shared/src/Skyline --configuration Release
        dotnet nuget push Shared/src/Skyline/bin/Release/Skyline.*.nupkg -k ${APIKEY} -s https://www.nuget.org/api/v2/package
      env:
        APIKEY: ${{ secrets.nuget }}
